application: gtaiesec
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /js
  static_dir: static/js
- url: /css
  static_dir: static/css
- url: /images
  static_dir: static/images
- url: .*
  script: handlers.app
  secure: always

- url: /_ah/spi/.*
  script: main.application
  
libraries:
- name: pycrypto
  version: latest

- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
  
- name: PIL
  version: "1.1.7"